### ISSUE TITLE
Build and run tests on pull requests

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/iwyu_buildbot#1]
It would be better and more convenient for developers if breakage on buildbot in [include-what-you-use/#212: Fix issue #127: macro locations](https://github.com/include-what-you-use/include-what-you-use/pull/212) was detected earlier.

Relevant buildbot concept is `try` which is documented [here](http://docs.buildbot.net/latest/manual/cmdline.html#try).

**Comment by kimgr** [comment]
This is now solved with the Travis config in the `include-what-you-use` project.
